# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/compute/v1/gpu_cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/compute/v1/gpu_cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from nebius.common.v1 import metadata_pb2 as nebius_dot_common_dot_v1_dot_metadata__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#nebius/compute/v1/gpu_cluster.proto\x12\x11nebius.compute.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a\x18nebius/annotations.proto\"\xa8\x01\n\nGpuCluster\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadata\x12/\n\x04spec\x18\x02 \x01(\x0b\x32!.nebius.compute.v1.GpuClusterSpec\x12\x33\n\x06status\x18\x03 \x01(\x0b\x32#.nebius.compute.v1.GpuClusterStatus\"7\n\x0eGpuClusterSpec\x12%\n\x11infiniband_fabric\x18\x01 \x01(\tB\n\xbaH\x03\xc8\x01\x01\xbaJ\x01\x02\"\xa5\x01\n\x10GpuClusterStatus\x12\x11\n\tinstances\x18\x01 \x03(\t\x12\x13\n\x0breconciling\x18\x02 \x01(\x08\x12]\n\x18infiniband_topology_path\x18\x03 \x01(\x0b\x32\x39.nebius.compute.v1.GpuClusterStatusInfinibandTopologyPathH\x00\x42\n\n\x08topology\"~\n&GpuClusterStatusInfinibandTopologyPath\x12T\n\tinstances\x18\x01 \x03(\x0b\x32\x41.nebius.compute.v1.GpuClusterStatusInfinibandTopologyPathInstance\"S\n.GpuClusterStatusInfinibandTopologyPathInstance\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x03(\tB^\n\x18\x61i.nebius.pub.compute.v1B\x0fGpuClusterProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.compute.v1.gpu_cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.nebius.pub.compute.v1B\017GpuClusterProtoP\001Z/github.com/nebius/gosdk/proto/nebius/compute/v1'
  _globals['_GPUCLUSTERSPEC'].fields_by_name['infiniband_fabric']._loaded_options = None
  _globals['_GPUCLUSTERSPEC'].fields_by_name['infiniband_fabric']._serialized_options = b'\272H\003\310\001\001\272J\001\002'
  _globals['_GPUCLUSTER']._serialized_start=147
  _globals['_GPUCLUSTER']._serialized_end=315
  _globals['_GPUCLUSTERSPEC']._serialized_start=317
  _globals['_GPUCLUSTERSPEC']._serialized_end=372
  _globals['_GPUCLUSTERSTATUS']._serialized_start=375
  _globals['_GPUCLUSTERSTATUS']._serialized_end=540
  _globals['_GPUCLUSTERSTATUSINFINIBANDTOPOLOGYPATH']._serialized_start=542
  _globals['_GPUCLUSTERSTATUSINFINIBANDTOPOLOGYPATH']._serialized_end=668
  _globals['_GPUCLUSTERSTATUSINFINIBANDTOPOLOGYPATHINSTANCE']._serialized_start=670
  _globals['_GPUCLUSTERSTATUSINFINIBANDTOPOLOGYPATHINSTANCE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
