# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/compute/v1/image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/compute/v1/image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius.common.v1 import metadata_pb2 as nebius_dot_common_dot_v1_dot_metadata__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dnebius/compute/v1/image.proto\x12\x11nebius.compute.v1\x1a\x1fnebius/common/v1/metadata.proto\x1a\x18nebius/annotations.proto\"\x99\x01\n\x05Image\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadata\x12*\n\x04spec\x18\x02 \x01(\x0b\x32\x1c.nebius.compute.v1.ImageSpec\x12.\n\x06status\x18\x03 \x01(\x0b\x32\x1e.nebius.compute.v1.ImageStatus\"\xf6\x01\n\tImageSpec\x12\x1e\n\x0b\x64\x65scription\x18\x01 \x01(\tB\x04\xbaJ\x01\x02H\x00\x88\x01\x01\x12\x1a\n\x0cimage_family\x18\x02 \x01(\tB\x04\xbaJ\x01\x02\x12\x15\n\x07version\x18\x03 \x01(\tB\x04\xbaJ\x01\x02\x12L\n\x10\x63pu_architecture\x18\x06 \x01(\x0e\x32,.nebius.compute.v1.ImageSpec.CPUArchitectureB\x04\xbaJ\x01\x02\"8\n\x0f\x43PUArchitecture\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05\x41MD64\x10\x01\x12\t\n\x05\x41RM64\x10\x02\x42\x0e\n\x0c_description\"\x85\x02\n\x0bImageStatus\x12\x33\n\x05state\x18\x01 \x01(\x0e\x32$.nebius.compute.v1.ImageStatus.State\x12\x19\n\x11state_description\x18\x02 \x01(\t\x12\x1a\n\x12storage_size_bytes\x18\x03 \x01(\x03\x12\x1b\n\x13min_disk_size_bytes\x18\x04 \x01(\x03\x12\x13\n\x0breconciling\x18\x05 \x01(\x08\"X\n\x05State\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0c\n\x08\x43REATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08UPDATING\x10\x03\x12\x0c\n\x08\x44\x45LETING\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x42Y\n\x18\x61i.nebius.pub.compute.v1B\nImageProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.compute.v1.image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.nebius.pub.compute.v1B\nImageProtoP\001Z/github.com/nebius/gosdk/proto/nebius/compute/v1'
  _globals['_IMAGESPEC'].fields_by_name['description']._loaded_options = None
  _globals['_IMAGESPEC'].fields_by_name['description']._serialized_options = b'\272J\001\002'
  _globals['_IMAGESPEC'].fields_by_name['image_family']._loaded_options = None
  _globals['_IMAGESPEC'].fields_by_name['image_family']._serialized_options = b'\272J\001\002'
  _globals['_IMAGESPEC'].fields_by_name['version']._loaded_options = None
  _globals['_IMAGESPEC'].fields_by_name['version']._serialized_options = b'\272J\001\002'
  _globals['_IMAGESPEC'].fields_by_name['cpu_architecture']._loaded_options = None
  _globals['_IMAGESPEC'].fields_by_name['cpu_architecture']._serialized_options = b'\272J\001\002'
  _globals['_IMAGE']._serialized_start=112
  _globals['_IMAGE']._serialized_end=265
  _globals['_IMAGESPEC']._serialized_start=268
  _globals['_IMAGESPEC']._serialized_end=514
  _globals['_IMAGESPEC_CPUARCHITECTURE']._serialized_start=442
  _globals['_IMAGESPEC_CPUARCHITECTURE']._serialized_end=498
  _globals['_IMAGESTATUS']._serialized_start=517
  _globals['_IMAGESTATUS']._serialized_end=778
  _globals['_IMAGESTATUS_STATE']._serialized_start=690
  _globals['_IMAGESTATUS_STATE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
