# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/compute/v1/maintenance_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/compute/v1/maintenance_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius import annotations_pb2 as nebius_dot_annotations__pb2
from nebius.compute.v1 import maintenance_event_pb2 as nebius_dot_compute_dot_v1_dot_maintenance__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+nebius/compute/v1/maintenance_service.proto\x12\x11nebius.compute.v1\x1a\x18nebius/annotations.proto\x1a)nebius/compute/v1/maintenance_event.proto\";\n$GetMaintenanceEventByInstanceRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"X\n\x1cListMaintenanceEventsRequest\x12\x11\n\tparent_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x03 \x01(\x03\x12\x12\n\npage_token\x18\x04 \x01(\t\"l\n\x1dListMaintenanceEventsResponse\x12\x32\n\x05items\x18\x01 \x03(\x0b\x32#.nebius.compute.v1.MaintenanceEvent\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\x80\x02\n\x12MaintenanceService\x12m\n\rGetByInstance\x12\x37.nebius.compute.v1.GetMaintenanceEventByInstanceRequest\x1a#.nebius.compute.v1.MaintenanceEvent\x12o\n\nListActive\x12/.nebius.compute.v1.ListMaintenanceEventsRequest\x1a\x30.nebius.compute.v1.ListMaintenanceEventsResponse\x1a\n\xbaJ\x07\x63omputeBf\n\x18\x61i.nebius.pub.compute.v1B\x17MaintenanceServiceProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.compute.v1.maintenance_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.nebius.pub.compute.v1B\027MaintenanceServiceProtoP\001Z/github.com/nebius/gosdk/proto/nebius/compute/v1'
  _globals['_MAINTENANCESERVICE']._loaded_options = None
  _globals['_MAINTENANCESERVICE']._serialized_options = b'\272J\007compute'
  _globals['_GETMAINTENANCEEVENTBYINSTANCEREQUEST']._serialized_start=135
  _globals['_GETMAINTENANCEEVENTBYINSTANCEREQUEST']._serialized_end=194
  _globals['_LISTMAINTENANCEEVENTSREQUEST']._serialized_start=196
  _globals['_LISTMAINTENANCEEVENTSREQUEST']._serialized_end=284
  _globals['_LISTMAINTENANCEEVENTSRESPONSE']._serialized_start=286
  _globals['_LISTMAINTENANCEEVENTSRESPONSE']._serialized_end=394
  _globals['_MAINTENANCESERVICE']._serialized_start=397
  _globals['_MAINTENANCESERVICE']._serialized_end=653
# @@protoc_insertion_point(module_scope)
