# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/compute/v1/maintenance_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/compute/v1/maintenance_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)nebius/compute/v1/maintenance_event.proto\x12\x11nebius.compute.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18nebius/annotations.proto\"\x96\x01\n\x10MaintenanceEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\x04spec\x18\x02 \x01(\x0b\x32\'.nebius.compute.v1.MaintenanceEventSpec\x12?\n\x06status\x18\x03 \x01(\x0b\x32).nebius.compute.v1.MaintenanceEventStatusB\x04\xbaJ\x01\x05\"0\n\x14MaintenanceEventSpec\x12\x18\n\nis_planned\x18\x05 \x01(\x08\x42\x04\xbaJ\x01\x02\"\xe8\x01\n\x16MaintenanceEventStatus\x12\x16\n\x0emaintenance_id\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x66inished_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0fsla_deadline_ts\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x18support_center_ticket_id\x18\t \x01(\tBd\n\x18\x61i.nebius.pub.compute.v1B\x15MaintenanceEventProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.compute.v1.maintenance_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.nebius.pub.compute.v1B\025MaintenanceEventProtoP\001Z/github.com/nebius/gosdk/proto/nebius/compute/v1'
  _globals['_MAINTENANCEEVENT'].fields_by_name['status']._loaded_options = None
  _globals['_MAINTENANCEEVENT'].fields_by_name['status']._serialized_options = b'\272J\001\005'
  _globals['_MAINTENANCEEVENTSPEC'].fields_by_name['is_planned']._loaded_options = None
  _globals['_MAINTENANCEEVENTSPEC'].fields_by_name['is_planned']._serialized_options = b'\272J\001\002'
  _globals['_MAINTENANCEEVENT']._serialized_start=124
  _globals['_MAINTENANCEEVENT']._serialized_end=274
  _globals['_MAINTENANCEEVENTSPEC']._serialized_start=276
  _globals['_MAINTENANCEEVENTSPEC']._serialized_end=324
  _globals['_MAINTENANCEEVENTSTATUS']._serialized_start=327
  _globals['_MAINTENANCEEVENTSTATUS']._serialized_end=559
# @@protoc_insertion_point(module_scope)
