# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/compute/v1/network_interface.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/compute/v1/network_interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)nebius/compute/v1/network_interface.proto\x12\x11nebius.compute.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x18nebius/annotations.proto\"\x9c\x02\n\x14NetworkInterfaceSpec\x12\x1d\n\tsubnet_id\x18\x01 \x01(\tB\n\xbaH\x03\xc8\x01\x01\xbaJ\x01\x02\x12\x34\n\x04name\x18\x02 \x01(\tB&\xbaH\x1fr\x1a\x10\x01\x18<2\x14^[0-9a-z][0-9a-z-]*$\xc8\x01\x01\xbaJ\x01\x02\x12=\n\nip_address\x18\x03 \x01(\x0b\x32\x1c.nebius.compute.v1.IPAddressB\x0b\xbaH\x03\xc8\x01\x01\xbaJ\x02\x06\x02\x12\x43\n\x11public_ip_address\x18\x04 \x01(\x0b\x32\".nebius.compute.v1.PublicIPAddressB\x04\xbaJ\x01\x06\x12+\n\x07\x61liases\x18\x06 \x03(\x0b\x32\x1a.nebius.compute.v1.IPAlias\"\"\n\tIPAddress\x12\x15\n\rallocation_id\x18\x01 \x01(\t\"H\n\x0fPublicIPAddress\x12\x17\n\rallocation_id\x18\x01 \x01(\tH\x00\x12\x0e\n\x06static\x18\x03 \x01(\x08\x42\x0c\n\nallocation\"(\n\x07IPAlias\x12\x1d\n\rallocation_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\"\x8a\x02\n\x16NetworkInterfaceStatus\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x36\n\nip_address\x18\x03 \x01(\x0b\x32\".nebius.compute.v1.IPAddressStatus\x12\x43\n\x11public_ip_address\x18\x04 \x01(\x0b\x32(.nebius.compute.v1.PublicIPAddressStatus\x12\x33\n\x07\x61liases\x18\x06 \x01(\x0b\x32\".nebius.compute.v1.IPAliasesStatus\x12\x13\n\x0bmac_address\x18\x07 \x01(\t\x12\x0c\n\x04\x66qdn\x18\t \x01(\t\"9\n\x0fIPAddressStatus\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x15\n\rallocation_id\x18\x02 \x01(\t\"O\n\x15PublicIPAddressStatus\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x15\n\rallocation_id\x18\x02 \x01(\t\x12\x0e\n\x06static\x18\x03 \x01(\x08\" \n\x0fIPAliasesStatus\x12\r\n\x05\x63idrs\x18\x02 \x03(\tBd\n\x18\x61i.nebius.pub.compute.v1B\x15NetworkInterfaceProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.compute.v1.network_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.nebius.pub.compute.v1B\025NetworkInterfaceProtoP\001Z/github.com/nebius/gosdk/proto/nebius/compute/v1'
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['subnet_id']._loaded_options = None
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['subnet_id']._serialized_options = b'\272H\003\310\001\001\272J\001\002'
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['name']._loaded_options = None
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['name']._serialized_options = b'\272H\037r\032\020\001\030<2\024^[0-9a-z][0-9a-z-]*$\310\001\001\272J\001\002'
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['ip_address']._loaded_options = None
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['ip_address']._serialized_options = b'\272H\003\310\001\001\272J\002\006\002'
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['public_ip_address']._loaded_options = None
  _globals['_NETWORKINTERFACESPEC'].fields_by_name['public_ip_address']._serialized_options = b'\272J\001\006'
  _globals['_IPALIAS'].fields_by_name['allocation_id']._loaded_options = None
  _globals['_IPALIAS'].fields_by_name['allocation_id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_NETWORKINTERFACESPEC']._serialized_start=120
  _globals['_NETWORKINTERFACESPEC']._serialized_end=404
  _globals['_IPADDRESS']._serialized_start=406
  _globals['_IPADDRESS']._serialized_end=440
  _globals['_PUBLICIPADDRESS']._serialized_start=442
  _globals['_PUBLICIPADDRESS']._serialized_end=514
  _globals['_IPALIAS']._serialized_start=516
  _globals['_IPALIAS']._serialized_end=556
  _globals['_NETWORKINTERFACESTATUS']._serialized_start=559
  _globals['_NETWORKINTERFACESTATUS']._serialized_end=825
  _globals['_IPADDRESSSTATUS']._serialized_start=827
  _globals['_IPADDRESSSTATUS']._serialized_end=884
  _globals['_PUBLICIPADDRESSSTATUS']._serialized_start=886
  _globals['_PUBLICIPADDRESSSTATUS']._serialized_end=965
  _globals['_IPALIASESSTATUS']._serialized_start=967
  _globals['_IPALIASESSTATUS']._serialized_end=999
# @@protoc_insertion_point(module_scope)
