# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/compute/v1/platform.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/compute/v1/platform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius import annotations_pb2 as nebius_dot_annotations__pb2
from nebius.common.v1 import metadata_pb2 as nebius_dot_common_dot_v1_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n nebius/compute/v1/platform.proto\x12\x11nebius.compute.v1\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\"\xa8\x01\n\x08Platform\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadata\x12-\n\x04spec\x18\x02 \x01(\x0b\x32\x1f.nebius.compute.v1.PlatformSpec\x12\x37\n\x06status\x18\x03 \x01(\x0b\x32!.nebius.compute.v1.PlatformStatusB\x04\xbaJ\x01\x05\"\xd3\x01\n\x0cPlatformSpec\x12*\n\x07presets\x18\x01 \x03(\x0b\x32\x19.nebius.compute.v1.Preset\x12\x1c\n\x14gpu_count_quota_type\x18\x03 \x01(\t\x12\x1b\n\x13human_readable_name\x18\x04 \x01(\t\x12\x1b\n\x13\x61llow_preset_change\x18\x05 \x01(\x08\x12!\n\x19short_human_readable_name\x18\n \x01(\t\x12\x1c\n\x14gpu_memory_gibibytes\x18\x0b \x01(\x05\"k\n\x06Preset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\tresources\x18\x02 \x01(\x0b\x32\".nebius.compute.v1.PresetResources\x12\x1c\n\x14\x61llow_gpu_clustering\x18\x03 \x01(\x08\"\xc1\x01\n\x0fPresetResources\x12\x18\n\nvcpu_count\x18\x01 \x01(\x05\x42\x04\xbaJ\x01\x05\x12\x18\n\x10memory_gibibytes\x18\x03 \x01(\x05\x12\x11\n\tgpu_count\x18\x04 \x01(\x05\x12g\n\x14gpu_memory_gibibytes\x18\x06 \x01(\x05\x42I\x18\x01\xd2JD\n\n2026-01-10\x12\x36Use field \'platform.spec.gpu_memory_gibibytes\' instead\"2\n\x0ePlatformStatus\x12 \n\x18\x61llowed_for_preemptibles\x18\x03 \x01(\x08\x42\\\n\x18\x61i.nebius.pub.compute.v1B\rPlatformProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.compute.v1.platform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.nebius.pub.compute.v1B\rPlatformProtoP\001Z/github.com/nebius/gosdk/proto/nebius/compute/v1'
  _globals['_PLATFORM'].fields_by_name['status']._loaded_options = None
  _globals['_PLATFORM'].fields_by_name['status']._serialized_options = b'\272J\001\005'
  _globals['_PRESETRESOURCES'].fields_by_name['vcpu_count']._loaded_options = None
  _globals['_PRESETRESOURCES'].fields_by_name['vcpu_count']._serialized_options = b'\272J\001\005'
  _globals['_PRESETRESOURCES'].fields_by_name['gpu_memory_gibibytes']._loaded_options = None
  _globals['_PRESETRESOURCES'].fields_by_name['gpu_memory_gibibytes']._serialized_options = b'\030\001\322JD\n\n2026-01-10\0226Use field \'platform.spec.gpu_memory_gibibytes\' instead'
  _globals['_PLATFORM']._serialized_start=115
  _globals['_PLATFORM']._serialized_end=283
  _globals['_PLATFORMSPEC']._serialized_start=286
  _globals['_PLATFORMSPEC']._serialized_end=497
  _globals['_PRESET']._serialized_start=499
  _globals['_PRESET']._serialized_end=606
  _globals['_PRESETRESOURCES']._serialized_start=609
  _globals['_PRESETRESOURCES']._serialized_end=802
  _globals['_PLATFORMSTATUS']._serialized_start=804
  _globals['_PLATFORMSTATUS']._serialized_end=854
# @@protoc_insertion_point(module_scope)
