# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/compute/v1/platform_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/compute/v1/platform_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius import annotations_pb2 as nebius_dot_annotations__pb2
from nebius.common.v1 import metadata_pb2 as nebius_dot_common_dot_v1_dot_metadata__pb2
from nebius.compute.v1 import platform_pb2 as nebius_dot_compute_dot_v1_dot_platform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(nebius/compute/v1/platform_service.proto\x12\x11nebius.compute.v1\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/compute/v1/platform.proto\"P\n\x14ListPlatformsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x03\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x11\n\tparent_id\x18\x03 \x01(\t\"\\\n\x15ListPlatformsResponse\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.nebius.compute.v1.Platform\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xc6\x01\n\x0fPlatformService\x12L\n\tGetByName\x12\".nebius.common.v1.GetByNameRequest\x1a\x1b.nebius.compute.v1.Platform\x12Y\n\x04List\x12\'.nebius.compute.v1.ListPlatformsRequest\x1a(.nebius.compute.v1.ListPlatformsResponse\x1a\n\xbaJ\x07\x63omputeBc\n\x18\x61i.nebius.pub.compute.v1B\x14PlatformServiceProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.compute.v1.platform_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.nebius.pub.compute.v1B\024PlatformServiceProtoP\001Z/github.com/nebius/gosdk/proto/nebius/compute/v1'
  _globals['_PLATFORMSERVICE']._loaded_options = None
  _globals['_PLATFORMSERVICE']._serialized_options = b'\272J\007compute'
  _globals['_LISTPLATFORMSREQUEST']._serialized_start=156
  _globals['_LISTPLATFORMSREQUEST']._serialized_end=236
  _globals['_LISTPLATFORMSRESPONSE']._serialized_start=238
  _globals['_LISTPLATFORMSRESPONSE']._serialized_end=330
  _globals['_PLATFORMSERVICE']._serialized_start=333
  _globals['_PLATFORMSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
