# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/common/v1/operation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/common/v1/operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n nebius/common/v1/operation.proto\x12\x10nebius.common.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x18nebius/annotations.proto\"\x9f\x04\n\tOperation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncreated_by\x18\x04 \x01(\t\x12/\n\x0b\x66inished_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x07request\x18\x06 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x66\n\x0frequest_headers\x18\x0b \x03(\x0b\x32/.nebius.common.v1.Operation.RequestHeadersEntryB\x1c\xbaH\x19\x9a\x01\x16\"\x14r\x12\x32\x10^[a-z][-a-z\\.]*$\x12\x13\n\x0bresource_id\x18\x07 \x01(\t\x12(\n\x06status\x18\n \x01(\x0b\x32\x12.google.rpc.StatusB\x04\xbaJ\x01\x06\x12+\n\rprogress_data\x18\t \x01(\x0b\x32\x14.google.protobuf.Any\x1a\x1f\n\rRequestHeader\x12\x0e\n\x06values\x18\x01 \x03(\t\x1a`\n\x13RequestHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x38\n\x05value\x18\x02 \x01(\x0b\x32).nebius.common.v1.Operation.RequestHeader:\x02\x38\x01\x42[\n\x17\x61i.nebius.pub.common.v1B\x0eOperationProtoP\x01Z.github.com/nebius/gosdk/proto/nebius/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.common.v1.operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027ai.nebius.pub.common.v1B\016OperationProtoP\001Z.github.com/nebius/gosdk/proto/nebius/common/v1'
  _globals['_OPERATION_REQUESTHEADERSENTRY']._loaded_options = None
  _globals['_OPERATION_REQUESTHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_OPERATION'].fields_by_name['request_headers']._loaded_options = None
  _globals['_OPERATION'].fields_by_name['request_headers']._serialized_options = b'\272H\031\232\001\026\"\024r\0222\020^[a-z][-a-z\\.]*$'
  _globals['_OPERATION'].fields_by_name['status']._loaded_options = None
  _globals['_OPERATION'].fields_by_name['status']._serialized_options = b'\272J\001\006'
  _globals['_OPERATION']._serialized_start=195
  _globals['_OPERATION']._serialized_end=738
  _globals['_OPERATION_REQUESTHEADER']._serialized_start=609
  _globals['_OPERATION_REQUESTHEADER']._serialized_end=640
  _globals['_OPERATION_REQUESTHEADERSENTRY']._serialized_start=642
  _globals['_OPERATION_REQUESTHEADERSENTRY']._serialized_end=738
# @@protoc_insertion_point(module_scope)
