# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/quotas/v1/quota_allowance_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/quotas/v1/quota_allowance_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2
from nebius.quotas.v1 import quota_allowance_pb2 as nebius_dot_quotas_dot_v1_dot_quota__allowance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.nebius/quotas/v1/quota_allowance_service.proto\x12\x10nebius.quotas.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x18nebius/annotations.proto\x1a&nebius/quotas/v1/quota_allowance.proto\"^\n\x1aListQuotaAllowancesRequest\x12\x19\n\tparent_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12\x11\n\tpage_size\x18\x02 \x01(\x03\x12\x12\n\npage_token\x18\x03 \x01(\t\"2\n\x18GetQuotaAllowanceRequest\x12\x16\n\x02id\x18\x01 \x01(\tB\n\xbaH\x03\xc8\x01\x01\xbaJ\x01\x03\"g\n\x1bListQuotaAllowancesResponse\x12/\n\x05items\x18\x01 \x03(\x0b\x32 .nebius.quotas.v1.QuotaAllowance\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"[\n\x10GetByNameRequest\x12\x19\n\tparent_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12\x14\n\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12\x16\n\x06region\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x32\xc5\x02\n\x15QuotaAllowanceService\x12\x63\n\x04List\x12,.nebius.quotas.v1.ListQuotaAllowancesRequest\x1a-.nebius.quotas.v1.ListQuotaAllowancesResponse\x12S\n\x03Get\x12*.nebius.quotas.v1.GetQuotaAllowanceRequest\x1a .nebius.quotas.v1.QuotaAllowance\x12Q\n\tGetByName\x12\".nebius.quotas.v1.GetByNameRequest\x1a .nebius.quotas.v1.QuotaAllowance\x1a\x1f\xbaJ\x1cquota-dispatcher.billing-cplBg\n\x17\x61i.nebius.pub.quotas.v1B\x1aQuotaAllowanceServiceProtoP\x01Z.github.com/nebius/gosdk/proto/nebius/quotas/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.quotas.v1.quota_allowance_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027ai.nebius.pub.quotas.v1B\032QuotaAllowanceServiceProtoP\001Z.github.com/nebius/gosdk/proto/nebius/quotas/v1'
  _globals['_LISTQUOTAALLOWANCESREQUEST'].fields_by_name['parent_id']._loaded_options = None
  _globals['_LISTQUOTAALLOWANCESREQUEST'].fields_by_name['parent_id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GETQUOTAALLOWANCEREQUEST'].fields_by_name['id']._loaded_options = None
  _globals['_GETQUOTAALLOWANCEREQUEST'].fields_by_name['id']._serialized_options = b'\272H\003\310\001\001\272J\001\003'
  _globals['_GETBYNAMEREQUEST'].fields_by_name['parent_id']._loaded_options = None
  _globals['_GETBYNAMEREQUEST'].fields_by_name['parent_id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GETBYNAMEREQUEST'].fields_by_name['name']._loaded_options = None
  _globals['_GETBYNAMEREQUEST'].fields_by_name['name']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GETBYNAMEREQUEST'].fields_by_name['region']._loaded_options = None
  _globals['_GETBYNAMEREQUEST'].fields_by_name['region']._serialized_options = b'\272H\003\310\001\001'
  _globals['_QUOTAALLOWANCESERVICE']._loaded_options = None
  _globals['_QUOTAALLOWANCESERVICE']._serialized_options = b'\272J\034quota-dispatcher.billing-cpl'
  _globals['_LISTQUOTAALLOWANCESREQUEST']._serialized_start=163
  _globals['_LISTQUOTAALLOWANCESREQUEST']._serialized_end=257
  _globals['_GETQUOTAALLOWANCEREQUEST']._serialized_start=259
  _globals['_GETQUOTAALLOWANCEREQUEST']._serialized_end=309
  _globals['_LISTQUOTAALLOWANCESRESPONSE']._serialized_start=311
  _globals['_LISTQUOTAALLOWANCESRESPONSE']._serialized_end=414
  _globals['_GETBYNAMEREQUEST']._serialized_start=416
  _globals['_GETBYNAMEREQUEST']._serialized_end=507
  _globals['_QUOTAALLOWANCESERVICE']._serialized_start=510
  _globals['_QUOTAALLOWANCESERVICE']._serialized_end=835
# @@protoc_insertion_point(module_scope)
