# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nebius.billing.v1alpha1 import calculator_service_pb2 as nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nebius/billing/v1alpha1/calculator_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculatorServiceStub(object):
    """Calculator service for estimating resource costs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Estimate = channel.unary_unary(
                '/nebius.billing.v1alpha1.CalculatorService/Estimate',
                request_serializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateRequest.SerializeToString,
                response_deserializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateResponse.FromString,
                _registered_method=True)
        self.EstimateBatch = channel.unary_unary(
                '/nebius.billing.v1alpha1.CalculatorService/EstimateBatch',
                request_serializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateBatchRequest.SerializeToString,
                response_deserializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateBatchResponse.FromString,
                _registered_method=True)


class CalculatorServiceServicer(object):
    """Calculator service for estimating resource costs.
    """

    def Estimate(self, request, context):
        """Estimates prices for a single resource.
        Returns both hourly and monthly cost estimates for the specified resource configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateBatch(self, request, context):
        """Estimates prices for multiple resources.
        Returns aggregated hourly and monthly cost estimates for all specified resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Estimate': grpc.unary_unary_rpc_method_handler(
                    servicer.Estimate,
                    request_deserializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateRequest.FromString,
                    response_serializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateResponse.SerializeToString,
            ),
            'EstimateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateBatch,
                    request_deserializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateBatchRequest.FromString,
                    response_serializer=nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nebius.billing.v1alpha1.CalculatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nebius.billing.v1alpha1.CalculatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculatorService(object):
    """Calculator service for estimating resource costs.
    """

    @staticmethod
    def Estimate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nebius.billing.v1alpha1.CalculatorService/Estimate',
            nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateRequest.SerializeToString,
            nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nebius.billing.v1alpha1.CalculatorService/EstimateBatch',
            nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateBatchRequest.SerializeToString,
            nebius_dot_billing_dot_v1alpha1_dot_calculator__service__pb2.EstimateBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
