# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nebius/billing/v1alpha1/calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nebius/billing/v1alpha1/calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius.compute.v1 import disk_service_pb2 as nebius_dot_compute_dot_v1_dot_disk__service__pb2
from nebius.compute.v1 import filesystem_service_pb2 as nebius_dot_compute_dot_v1_dot_filesystem__service__pb2
from nebius.compute.v1 import instance_service_pb2 as nebius_dot_compute_dot_v1_dot_instance__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(nebius/billing/v1alpha1/calculator.proto\x12\x17nebius.billing.v1alpha1\x1a$nebius/compute/v1/disk_service.proto\x1a*nebius/compute/v1/filesystem_service.proto\x1a(nebius/compute/v1/instance_service.proto\"\xee\x03\n\x0cResourceSpec\x12I\n\x15\x63ompute_instance_spec\x18\x64 \x01(\x0b\x32(.nebius.compute.v1.CreateInstanceRequestH\x00\x12P\n\x1c\x63ompute_instance_update_spec\x18\x65 \x01(\x0b\x32(.nebius.compute.v1.UpdateInstanceRequestH\x00\x12\x41\n\x11\x63ompute_disk_spec\x18\x66 \x01(\x0b\x32$.nebius.compute.v1.CreateDiskRequestH\x00\x12H\n\x18\x63ompute_disk_update_spec\x18g \x01(\x0b\x32$.nebius.compute.v1.UpdateDiskRequestH\x00\x12M\n\x17\x63ompute_filesystem_spec\x18h \x01(\x0b\x32*.nebius.compute.v1.CreateFilesystemRequestH\x00\x12T\n\x1e\x63ompute_filesystem_update_spec\x18i \x01(\x0b\x32*.nebius.compute.v1.UpdateFilesystemRequestH\x00\x42\x0f\n\rresource_spec\"^\n\x11ResourceGroupCost\x12<\n\x07general\x18\n \x01(\x0b\x32).nebius.billing.v1alpha1.GeneralTotalCostH\x00\x42\x0b\n\tcost_type\"I\n\x10GeneralTotalCost\x12\x35\n\x05total\x18\x01 \x01(\x0b\x32&.nebius.billing.v1alpha1.CostBreakdown\"L\n\x13GeneralResourceCost\x12\x35\n\x05total\x18\x01 \x01(\x0b\x32&.nebius.billing.v1alpha1.CostBreakdown\"3\n\rCostBreakdown\x12\x0c\n\x04\x63ost\x18\x02 \x01(\t\x12\x14\n\x0c\x63ost_rounded\x18\x03 \x01(\tBj\n\x1e\x61i.nebius.pub.billing.v1alpha1B\x0f\x43\x61lculatorProtoP\x01Z5github.com/nebius/gosdk/proto/nebius/billing/v1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.billing.v1alpha1.calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036ai.nebius.pub.billing.v1alpha1B\017CalculatorProtoP\001Z5github.com/nebius/gosdk/proto/nebius/billing/v1alpha1'
  _globals['_RESOURCESPEC']._serialized_start=194
  _globals['_RESOURCESPEC']._serialized_end=688
  _globals['_RESOURCEGROUPCOST']._serialized_start=690
  _globals['_RESOURCEGROUPCOST']._serialized_end=784
  _globals['_GENERALTOTALCOST']._serialized_start=786
  _globals['_GENERALTOTALCOST']._serialized_end=859
  _globals['_GENERALRESOURCECOST']._serialized_start=861
  _globals['_GENERALRESOURCECOST']._serialized_end=937
  _globals['_COSTBREAKDOWN']._serialized_start=939
  _globals['_COSTBREAKDOWN']._serialized_end=990
# @@protoc_insertion_point(module_scope)
